// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/smallnest/rpcx/server"
	"github.com/weplanx/transfer/app"
	"github.com/weplanx/transfer/bootstrap"
	"github.com/weplanx/transfer/common"
)

// Injectors from wire.go:

func App(value *common.Values) (*server.Server, error) {
	client, err := bootstrap.UseMongoDB(value)
	if err != nil {
		return nil, err
	}
	database := bootstrap.UseDatabase(client, value)
	conn, err := bootstrap.UseNats(value)
	if err != nil {
		return nil, err
	}
	jetStreamContext, err := bootstrap.UseJetStream(conn)
	if err != nil {
		return nil, err
	}
	api := &app.API{
		Values: value,
		Db:     database,
		Nats:   conn,
		Js:     jetStreamContext,
	}
	serverServer, err := app.New(value, database, api)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
