// Code generated by protoc-gen-go. DO NOT EDIT.
// source: router.proto

package elastic_transfer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NoParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoParameter) Reset()         { *m = NoParameter{} }
func (m *NoParameter) String() string { return proto.CompactTextString(m) }
func (*NoParameter) ProtoMessage()    {}
func (*NoParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{0}
}

func (m *NoParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoParameter.Unmarshal(m, b)
}
func (m *NoParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoParameter.Marshal(b, m, deterministic)
}
func (m *NoParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoParameter.Merge(m, src)
}
func (m *NoParameter) XXX_Size() int {
	return xxx_messageInfo_NoParameter.Size(m)
}
func (m *NoParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_NoParameter.DiscardUnknown(m)
}

var xxx_messageInfo_NoParameter proto.InternalMessageInfo

type Response struct {
	Error                uint32   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Information struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Index                string   `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Validate             string   `protobuf:"bytes,3,opt,name=validate,proto3" json:"validate,omitempty"`
	Topic                string   `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Key                  string   `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Information) Reset()         { *m = Information{} }
func (m *Information) String() string { return proto.CompactTextString(m) }
func (*Information) ProtoMessage()    {}
func (*Information) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{2}
}

func (m *Information) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Information.Unmarshal(m, b)
}
func (m *Information) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Information.Marshal(b, m, deterministic)
}
func (m *Information) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Information.Merge(m, src)
}
func (m *Information) XXX_Size() int {
	return xxx_messageInfo_Information.Size(m)
}
func (m *Information) XXX_DiscardUnknown() {
	xxx_messageInfo_Information.DiscardUnknown(m)
}

var xxx_messageInfo_Information proto.InternalMessageInfo

func (m *Information) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Information) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Information) GetValidate() string {
	if m != nil {
		return m.Validate
	}
	return ""
}

func (m *Information) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Information) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetParameter struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParameter) Reset()         { *m = GetParameter{} }
func (m *GetParameter) String() string { return proto.CompactTextString(m) }
func (*GetParameter) ProtoMessage()    {}
func (*GetParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{3}
}

func (m *GetParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParameter.Unmarshal(m, b)
}
func (m *GetParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParameter.Marshal(b, m, deterministic)
}
func (m *GetParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParameter.Merge(m, src)
}
func (m *GetParameter) XXX_Size() int {
	return xxx_messageInfo_GetParameter.Size(m)
}
func (m *GetParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParameter.DiscardUnknown(m)
}

var xxx_messageInfo_GetParameter proto.InternalMessageInfo

func (m *GetParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type GetResponse struct {
	Error                uint32       `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Msg                  string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *Information `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *GetResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetResponse) GetData() *Information {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListsParameter struct {
	Identity             []string `protobuf:"bytes,1,rep,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListsParameter) Reset()         { *m = ListsParameter{} }
func (m *ListsParameter) String() string { return proto.CompactTextString(m) }
func (*ListsParameter) ProtoMessage()    {}
func (*ListsParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{5}
}

func (m *ListsParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListsParameter.Unmarshal(m, b)
}
func (m *ListsParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListsParameter.Marshal(b, m, deterministic)
}
func (m *ListsParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListsParameter.Merge(m, src)
}
func (m *ListsParameter) XXX_Size() int {
	return xxx_messageInfo_ListsParameter.Size(m)
}
func (m *ListsParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListsParameter.DiscardUnknown(m)
}

var xxx_messageInfo_ListsParameter proto.InternalMessageInfo

func (m *ListsParameter) GetIdentity() []string {
	if m != nil {
		return m.Identity
	}
	return nil
}

type ListsResponse struct {
	Error                uint32         `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Msg                  string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*Information `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListsResponse) Reset()         { *m = ListsResponse{} }
func (m *ListsResponse) String() string { return proto.CompactTextString(m) }
func (*ListsResponse) ProtoMessage()    {}
func (*ListsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{6}
}

func (m *ListsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListsResponse.Unmarshal(m, b)
}
func (m *ListsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListsResponse.Marshal(b, m, deterministic)
}
func (m *ListsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListsResponse.Merge(m, src)
}
func (m *ListsResponse) XXX_Size() int {
	return xxx_messageInfo_ListsResponse.Size(m)
}
func (m *ListsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListsResponse proto.InternalMessageInfo

func (m *ListsResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *ListsResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListsResponse) GetData() []*Information {
	if m != nil {
		return m.Data
	}
	return nil
}

type AllResponse struct {
	Error                uint32   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllResponse) Reset()         { *m = AllResponse{} }
func (m *AllResponse) String() string { return proto.CompactTextString(m) }
func (*AllResponse) ProtoMessage()    {}
func (*AllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{7}
}

func (m *AllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllResponse.Unmarshal(m, b)
}
func (m *AllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllResponse.Marshal(b, m, deterministic)
}
func (m *AllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllResponse.Merge(m, src)
}
func (m *AllResponse) XXX_Size() int {
	return xxx_messageInfo_AllResponse.Size(m)
}
func (m *AllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllResponse proto.InternalMessageInfo

func (m *AllResponse) GetError() uint32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *AllResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AllResponse) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteParameter struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteParameter) Reset()         { *m = DeleteParameter{} }
func (m *DeleteParameter) String() string { return proto.CompactTextString(m) }
func (*DeleteParameter) ProtoMessage()    {}
func (*DeleteParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{8}
}

func (m *DeleteParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteParameter.Unmarshal(m, b)
}
func (m *DeleteParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteParameter.Marshal(b, m, deterministic)
}
func (m *DeleteParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteParameter.Merge(m, src)
}
func (m *DeleteParameter) XXX_Size() int {
	return xxx_messageInfo_DeleteParameter.Size(m)
}
func (m *DeleteParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteParameter.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteParameter proto.InternalMessageInfo

func (m *DeleteParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type PushParameter struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushParameter) Reset()         { *m = PushParameter{} }
func (m *PushParameter) String() string { return proto.CompactTextString(m) }
func (*PushParameter) ProtoMessage()    {}
func (*PushParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_367072455c71aedc, []int{9}
}

func (m *PushParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushParameter.Unmarshal(m, b)
}
func (m *PushParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushParameter.Marshal(b, m, deterministic)
}
func (m *PushParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushParameter.Merge(m, src)
}
func (m *PushParameter) XXX_Size() int {
	return xxx_messageInfo_PushParameter.Size(m)
}
func (m *PushParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_PushParameter.DiscardUnknown(m)
}

var xxx_messageInfo_PushParameter proto.InternalMessageInfo

func (m *PushParameter) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *PushParameter) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*NoParameter)(nil), "elastic.transfer.NoParameter")
	proto.RegisterType((*Response)(nil), "elastic.transfer.Response")
	proto.RegisterType((*Information)(nil), "elastic.transfer.Information")
	proto.RegisterType((*GetParameter)(nil), "elastic.transfer.GetParameter")
	proto.RegisterType((*GetResponse)(nil), "elastic.transfer.GetResponse")
	proto.RegisterType((*ListsParameter)(nil), "elastic.transfer.ListsParameter")
	proto.RegisterType((*ListsResponse)(nil), "elastic.transfer.ListsResponse")
	proto.RegisterType((*AllResponse)(nil), "elastic.transfer.AllResponse")
	proto.RegisterType((*DeleteParameter)(nil), "elastic.transfer.DeleteParameter")
	proto.RegisterType((*PushParameter)(nil), "elastic.transfer.PushParameter")
}

func init() { proto.RegisterFile("router.proto", fileDescriptor_367072455c71aedc) }

var fileDescriptor_367072455c71aedc = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xd1, 0x8e, 0xd2, 0x40,
	0x14, 0xdd, 0x3a, 0x40, 0x96, 0x5b, 0xaa, 0x9b, 0x89, 0x0f, 0x4d, 0x93, 0x55, 0x9c, 0xa7, 0x8d,
	0xd1, 0x26, 0xe2, 0x07, 0x98, 0x35, 0xae, 0x84, 0x64, 0x63, 0x48, 0xff, 0x60, 0xa4, 0x17, 0x19,
	0x29, 0x1d, 0x32, 0x73, 0x31, 0xf2, 0xec, 0x67, 0xf9, 0x73, 0xa6, 0x53, 0x20, 0x85, 0x16, 0x84,
	0xec, 0x5b, 0x6f, 0xe6, 0x9c, 0x73, 0xcf, 0xbd, 0x67, 0x3a, 0xd0, 0x33, 0x7a, 0x45, 0x68, 0xe2,
	0xa5, 0xd1, 0xa4, 0xf9, 0x0d, 0x66, 0xd2, 0x92, 0x9a, 0xc4, 0x64, 0x64, 0x6e, 0xa7, 0x68, 0x44,
	0x00, 0xfe, 0x37, 0x3d, 0x96, 0x46, 0x2e, 0x90, 0xd0, 0x88, 0x01, 0x5c, 0x27, 0x68, 0x97, 0x3a,
	0xb7, 0xc8, 0x5f, 0x42, 0x1b, 0x8d, 0xd1, 0x26, 0xf4, 0xfa, 0xde, 0x5d, 0x90, 0x94, 0x05, 0xbf,
	0x01, 0xb6, 0xb0, 0x3f, 0xc2, 0x67, 0x7d, 0xef, 0xae, 0x9b, 0x14, 0x9f, 0xe2, 0x8f, 0x07, 0xfe,
	0x28, 0x9f, 0x6a, 0xb3, 0x90, 0xa4, 0x74, 0xce, 0x23, 0xb8, 0x56, 0x29, 0xe6, 0xa4, 0x68, 0xed,
	0xa8, 0xdd, 0x64, 0x57, 0x17, 0x9a, 0x2a, 0x4f, 0xf1, 0xf7, 0x86, 0x5f, 0x16, 0x05, 0xe3, 0x97,
	0xcc, 0x54, 0x2a, 0x09, 0x43, 0x56, 0x32, 0xb6, 0x75, 0xc1, 0x20, 0xbd, 0x54, 0x93, 0xb0, 0x55,
	0x32, 0x5c, 0x51, 0xb8, 0x98, 0xe3, 0x3a, 0x6c, 0x97, 0x2e, 0xe6, 0xb8, 0x16, 0x6f, 0xa1, 0x37,
	0x44, 0xda, 0x4d, 0x72, 0xca, 0x85, 0x98, 0x81, 0x3f, 0x44, 0xba, 0x74, 0x50, 0xfe, 0x01, 0x5a,
	0xa9, 0x24, 0xe9, 0x2c, 0xfa, 0x83, 0xdb, 0xf8, 0x70, 0x99, 0x71, 0x65, 0x0b, 0x89, 0x83, 0x8a,
	0x77, 0xf0, 0xfc, 0x51, 0x59, 0xb2, 0xc7, 0x7c, 0xb1, 0x3d, 0x5f, 0x3f, 0x21, 0x70, 0xe8, 0x27,
	0x38, 0x63, 0xe7, 0x3a, 0x1b, 0x81, 0x7f, 0x9f, 0x65, 0x17, 0x77, 0xe2, 0x95, 0x4e, 0xdd, 0x8d,
	0xd4, 0x7b, 0x78, 0xf1, 0x05, 0x33, 0x24, 0x3c, 0x6f, 0xfb, 0x9f, 0x20, 0x18, 0xaf, 0xec, 0xec,
	0x2c, 0xf0, 0xae, 0x5f, 0x61, 0xa1, 0x57, 0xf6, 0x1b, 0xfc, 0x65, 0xd0, 0x49, 0xdc, 0xb5, 0xe6,
	0x5f, 0x81, 0x0d, 0x91, 0xf8, 0xab, 0xfa, 0xc4, 0xd5, 0xcb, 0x10, 0xdd, 0x36, 0x9e, 0x6f, 0x87,
	0x17, 0x57, 0xfc, 0x11, 0xda, 0x6e, 0xf3, 0xbc, 0x5f, 0x47, 0xee, 0x07, 0x18, 0xbd, 0x3e, 0x82,
	0xa8, 0xa8, 0x3d, 0x00, 0xbb, 0xcf, 0x32, 0xde, 0xd0, 0xb5, 0xf2, 0xaf, 0x35, 0x99, 0xaa, 0x24,
	0x22, 0xae, 0xf8, 0x67, 0x60, 0xe3, 0x15, 0xf1, 0xd3, 0x71, 0x46, 0x51, 0xfd, 0xb8, 0xa2, 0x31,
	0x82, 0x4e, 0x99, 0x0d, 0x7f, 0x53, 0xc7, 0x1d, 0xa4, 0xf6, 0x1f, 0xa9, 0x07, 0x68, 0x15, 0xb9,
	0xf1, 0x86, 0x05, 0xec, 0xe5, 0x79, 0x5a, 0xe6, 0x7b, 0xc7, 0x3d, 0x45, 0x1f, 0xff, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x25, 0x44, 0x08, 0x96, 0x9a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouterClient interface {
	Get(ctx context.Context, in *GetParameter, opts ...grpc.CallOption) (*GetResponse, error)
	Lists(ctx context.Context, in *ListsParameter, opts ...grpc.CallOption) (*ListsResponse, error)
	All(ctx context.Context, in *NoParameter, opts ...grpc.CallOption) (*AllResponse, error)
	Put(ctx context.Context, in *Information, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *DeleteParameter, opts ...grpc.CallOption) (*Response, error)
	Push(ctx context.Context, in *PushParameter, opts ...grpc.CallOption) (*Response, error)
}

type routerClient struct {
	cc *grpc.ClientConn
}

func NewRouterClient(cc *grpc.ClientConn) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) Get(ctx context.Context, in *GetParameter, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/elastic.transfer.Router/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Lists(ctx context.Context, in *ListsParameter, opts ...grpc.CallOption) (*ListsResponse, error) {
	out := new(ListsResponse)
	err := c.cc.Invoke(ctx, "/elastic.transfer.Router/Lists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) All(ctx context.Context, in *NoParameter, opts ...grpc.CallOption) (*AllResponse, error) {
	out := new(AllResponse)
	err := c.cc.Invoke(ctx, "/elastic.transfer.Router/All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Put(ctx context.Context, in *Information, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/elastic.transfer.Router/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Delete(ctx context.Context, in *DeleteParameter, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/elastic.transfer.Router/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Push(ctx context.Context, in *PushParameter, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/elastic.transfer.Router/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
type RouterServer interface {
	Get(context.Context, *GetParameter) (*GetResponse, error)
	Lists(context.Context, *ListsParameter) (*ListsResponse, error)
	All(context.Context, *NoParameter) (*AllResponse, error)
	Put(context.Context, *Information) (*Response, error)
	Delete(context.Context, *DeleteParameter) (*Response, error)
	Push(context.Context, *PushParameter) (*Response, error)
}

// UnimplementedRouterServer can be embedded to have forward compatible implementations.
type UnimplementedRouterServer struct {
}

func (*UnimplementedRouterServer) Get(ctx context.Context, req *GetParameter) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedRouterServer) Lists(ctx context.Context, req *ListsParameter) (*ListsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lists not implemented")
}
func (*UnimplementedRouterServer) All(ctx context.Context, req *NoParameter) (*AllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (*UnimplementedRouterServer) Put(ctx context.Context, req *Information) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedRouterServer) Delete(ctx context.Context, req *DeleteParameter) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedRouterServer) Push(ctx context.Context, req *PushParameter) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}

func RegisterRouterServer(s *grpc.Server, srv RouterServer) {
	s.RegisterService(&_Router_serviceDesc, srv)
}

func _Router_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elastic.transfer.Router/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Get(ctx, req.(*GetParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Lists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListsParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Lists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elastic.transfer.Router/Lists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Lists(ctx, req.(*ListsParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elastic.transfer.Router/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).All(ctx, req.(*NoParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Information)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elastic.transfer.Router/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Put(ctx, req.(*Information))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elastic.transfer.Router/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Delete(ctx, req.(*DeleteParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elastic.transfer.Router/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Push(ctx, req.(*PushParameter))
	}
	return interceptor(ctx, in, info, handler)
}

var _Router_serviceDesc = grpc.ServiceDesc{
	ServiceName: "elastic.transfer.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Router_Get_Handler,
		},
		{
			MethodName: "Lists",
			Handler:    _Router_Lists_Handler,
		},
		{
			MethodName: "All",
			Handler:    _Router_All_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Router_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Router_Delete_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _Router_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "router.proto",
}
